---
apiVersion: v1
kind: Namespace
metadata:
  name: rainfall
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: rainfall
  name: configuration
  labels:
    app: rainfall
data:
  config.yaml: |
    ---
    rainfall-data-client:
      URL: https://api.data.gov.sg/v1/environment/rainfall
      Location: Marina Gardens Drive
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rainfall
  name: rainfall
spec:
  selector:
    matchLabels:
      app: rainfall
  replicas: 1
  template:
    metadata:
      labels:
        app: rainfall
    spec:
      containers:
      - name: rainfall
        image: localhost:5000/mkucia/rainfall:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/config.yaml
          subPath: config.yaml
          readOnly: true
          name: configuration
      volumes:
      - name: configuration
        configMap:
          name: configuration
          items:
            - key: config.yaml
              path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  namespace: rainfall
  name: rainfall
  labels:
    app: rainfall
spec:
  selector:
    app: rainfall
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rainfall
  namespace: rainfall
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rainfall
            port:
              number: 8080
 